### PR TITLE
Iterators

### PR DESCRIPTION
**Pull request by dorkbox**
These are some changes to move towards direct iteration, instead of creating new iterators.

Here are the performance benchmarks (baseline is first, iterators is second). Not a huge change in  overall throughput, but less object creation and more consistent performance.

baseline

iterators

### CODE REVIEW

**Comment by dorkbox** [comment]
Hmm, I'll fix the merge conflicts. I thought I was on master, but clearly that was my branch and not the main one.

**Comment by dorkbox** [comment]
Updated

**Comment by dorkbox** [comment]
iterators, based on master

**Comment by bennidi** [comment]
Thanks for your contribution. I don't see much of a win in performance in the charts. From a design perspective the proposed code is worse than the current one, don't you think? At least there are now public interfaces meant as extension points which have dependency to an internal class in their signature. Do you feel that the performance gain really justifies the raise in code complexity?

I think that your work on the queue implementations looks much more promising.

**Comment by dorkbox** [comment]
Yea, I don't know if it's worth it, especially because it add complexity. It was mostly an exercise with exploring the cost of creating iterators.

I think the only change that is worth it is in [ReflectionUtils](https://github.com/dorkbox/mbassador/blob/iterators/src/main/java/net/engio/mbassy/common/ReflectionUtils.java#L19), where the recursive hashset is passed in, instead of creating a new one for each step in recursion. You could make it a regular hashset instead or, I can make a separate branch with just that change.

**Comment by bennidi** [comment]
I would gladly take that change but as a separate PR to keep the history clean. I think that the iterator changes make sense for your extreme performance bus but most likely not for this version of mbassador.

**Pull request closed without merging**
