### PR TITLE
Add ability to cancel events

### PR DESCRIPTION
**Pull request by nikoliazekter**
Sometimes there's a need to cancel event so other handlers won't get it. It theoretically should work good but I tested it only with synchronous events. If you approve this, I'll add unit tests if needed.

### CODE REVIEW

**Comment by bennidi** [comment]
I can not think of a use case where cancellation of a message publication is necessary. I think that the need to cancel a message that is already being published very likely indicates a problem in your code design.

The proposed code in your PR is not thread-safe and comes with various race conditions (for instance when publications are added while the map is being rehashed). Furthermore, it was really difficult to get the core stable and correctly synchronized. I don't want to add new code to it unless the new feature is really worth it.

**Comment by nikoliazekter** [comment]
I understand. Here's an example where cancellable events are useful https://github.com/MovingBlocks/Terasology/wiki/Events-and-Systems#consumable-events .

**Comment by nikoliazekter** [comment]
Thinking about it made me realize that "consume the event" sounds more correct than "cancel the event".

**Comment by tbee** [comment]
I'm currently searching for a way to cancel/consume events in mbassador, to support a PR adding this functionality I'll describe my use case. (I understand that this specific PR has technical issues.)

In my setup MBassador is used in a JEE environment to loosely couple some modules. Most events are handled synchronous and within a single UserTransaction. If one of the events runs into a problem and sets the UserTransaction to "rollback only" the sending of events is not cancelled; the following listeners will flood the logs with "transaction set to rollback only" exceptions. I need to be able to tell MBassador to cancel if such an situation occurs.

**Comment by bennidi** [comment]
I close this PR because it has not test code attached. It contains modification to core code and I assume that it introduces race conditions.
The requested feature would best be implemented with a custom dispatcher.

**Pull request closed without merging**
