### PR TITLE
Add support for interfaces

### PR DESCRIPTION
**Pull request by chriskingnet**
I have included the following (based on discussion from issue #67): 

- Added support for interfaces with handler methods defined
- Added support for enveloped configuration from handlers in interfaces
- Extended test cases to prove implemented

### CODE REVIEW

**Comment by bennidi** [comment]
Hey Chris, super nice that you took time to work on that feature. Code looks good as far as I can tell from a quick first glance. Weirdly the Travis CI build fails. Did you rebase your work on current master before submitting the PR?

**Comment by chriskingnet** [comment]
Hey @bennidi, no problem at all. Thanks for creating this project, I have used it happily for quite some time now, so was happy to be able to finally get around to submitting a PR for something :)

Yes, I did - it is at least showing me I am up to date with the upstream master. Having a quick look at the travis output, it seems to be complaining about something to do with an expired key? Is this a red-herring though, as I saw a build successfully ran just a few hours ago? (Albeit for a difference branch). Can hopefully spend a bit more time looking at this tomorrow!

**Comment by chriskingnet** [comment]
Forget what I said - reading the log properly, the expired key is nothing to do with the actual error. I don't know a lot about Travis CI, but it seems they might have dropped support for using OpenJDK6 in some way? https://github.com/travis-ci/travis-ci/issues/8199

Seems to fit with the error seen at the end of the output window.

**Comment by chriskingnet** [comment]
Let me know if there is anything I can do to help you with this. Also, what are your thoughts generally on maintaining support for Java6 in the future?

**Comment by bennidi** [comment]
Hey, thanks for keeping in touch. I will dedicate some time to this issue soon. Currently I am on a retreat until next week. But I guess an upgrade to Java 7 is easy and implications for Java 8 can be discussed, too.

**Comment by bennidi** [comment]
I merged your PR and made a new release. Congratulations and thank you.

**Comment by chriskingnet** [comment]
Great, and no problem. Thanks for all your work on this project, much appreciated. :-)

**Pull request merged**
