### PR TITLE
Made it possible to extend MessagePublication class

### PR DESCRIPTION
**Pull request by kolybelkin**

### CODE REVIEW

**Comment by bennidi** [comment]
What is the intent of this modification?

**Comment by kolybelkin** [comment]
Because it is not possible to extend the class because of private class. When you create child class you cannot override constructor, what is mandatory for extending it

**Comment by bennidi** [comment]
Interesting. What is the reason for extending MessagePulication? I am curious.

**Comment by kolybelkin** [comment]
I want to reduce garbage by using pool for event objects. The reason to override it is to add logic for returning the events back into the pool after processing them in all subscribers.

**Comment by kolybelkin** [comment]
Hi @bennidi, will it be merged/released?

**Pull request merged**
