### PR TITLE
Add Maven Central badge to Readme

### PR DESCRIPTION
**Pull request by leif81**
To help users discover latest published artifact.

### CODE REVIEW

**Comment by bennidi** [comment]
Thank you.

**Comment by bennidi** [comment]
WTF, man. Do I honestly have to review edits to README nowadays?

**Comment by leif81** [comment]
Not sure what you mean.

**Comment by bennidi** [comment]
README badge was broken after merge. I didn't see it until today and fixed it. Don't know what happened there but it showed the markdown source of that image include as unparsed. In your commit it looks fine actually.

**Comment by leif81** [comment]
Ooh interesting. Might have been related to the new markdown parser github rolled out recently. Sorry for the hassel. Glad to see it's working now.

**Pull request merged**
